CREATE DATABASE IF NOT EXISTS mysql_db;

CREATE USER 'mysql_user'@'localhost' IDENTIFIED BY 'MpNB7Daz8_QL7RYWPF9E';

GRANT ALL PRIVILEGES ON *.* TO 'mysql_user'@'localhost' WITH GRANT OPTION;

CREATE USER 'mysql_user'@'%' IDENTIFIED BY 'MpNB7Daz8_QL7RYWPF9E';

GRANT ALL PRIVILEGES ON *.* TO 'mysql_user'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;